server:
  port: 9002
spring:
  application:
    name: provider
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        metadata:
          version: prod
        server-addr: 127.0.0.1:8848
